FROM golang:1.19-alpine
RUN addgroup -g 1000 myuser && \
    adduser -D -u 1000 -G myuser myuser
RUN apk add --no-cache git
RUN go install github.com/go-delve/delve/cmd/dlv@latest
WORKDIR /app
COPY go.* .
RUN go mod download
RUN chown -R myuser:myuser /app && \
    chmod -R 755 /app
COPY . .
RUN --mount=type=cache,target=/root/.cache/go-build go build -gcflags "-N -l" -tags $BUILD_ENVIRONMENT -ldflags="-X github.com/datreeio/admission-webhook-datree/pkg/config.WebhookVersion=$WEBHOOK_VERSION"  -o webhook-datree 

USER myuser

ENTRYPOINT [ "dlv", "exec", "--headless", "--listen=:5555", "--api-version=2", "--", "/app/webhook-datree" ]


# --------------------------------

# # Use a smaller base image
# FROM golang:alpine AS build
# RUN go version
# # Install Git and Go
# RUN apk add --no-cache git go

# # Install dlv
# RUN go install github.com/go-delve/delve/cmd/dlv@latest

# # Set the working directory
# WORKDIR /app

# # Copy the Go module files
# COPY go.* .
# RUN go mod download
# RUN go mod tidy
# # Copy the source code
# COPY . .

# # Build the Go binary
# RUN go build -gcflags "-N -l" -tags $BUILD_ENVIRONMENT -ldflags="-X github.com/datreeio/admission-webhook-datree/pkg/config.WebhookVersion=$WEBHOOK_VERSION" -o webhook-datree

# # Use a smaller base image for the runtime environment
# FROM alpine:3.14
# COPY --from=build /go/bin/dlv /usr/local/bin/dlv
# # Add a non-root user
# RUN addgroup -g 1000 myuser && \
#     adduser -D -u 1000 -G myuser myuser

# # Set the working directory
# WORKDIR /app

# # Copy the Go binary from the build image
# COPY --from=build /app/webhook-datree .

# # Set the ownership and permissions
# RUN chown -R myuser:myuser /app && \
#     chmod -R 755 /app

# # Use the non-root user
# USER myuser

# # Set the entrypoint
# ENTRYPOINT [ "dlv", "exec", "--headless", "--listen=:5555", "--api-version=2", "--", "/app/webhook-datree" ]


# --------------------------------

# # Build stage
# FROM golang:alpine AS builder

# RUN apk add --no-cache git

# WORKDIR /app

# # Cache Go modules
# COPY go.mod go.sum ./
# RUN go mod download

# COPY . .
# RUN --mount=type=cache,target=/root/.cache/go-build go build -o webhook-datree \
#     -gcflags "-N -l" \
#     -tags $BUILD_ENVIRONMENT \
#     -ldflags="-X github.com/datreeio/admission-webhook-datree/pkg/config.WebhookVersion=$WEBHOOK_VERSION"
# RUN ls -lsah /root/.cache/go-build
# RUN which dlv
# # Final stage
# FROM golang:1.16-alpine

# RUN addgroup -g 1000 myuser && \
#     adduser -D -u 1000 -G myuser myuser

# USER myuser

# WORKDIR /app
# # Copy --from=builder /go/bin/dlv 
# COPY --from=builder /app/webhook-datree .

# ENTRYPOINT [ "dlv", "exec", "--headless", "--listen=:5555", "--api-version=2", "--", "/app/webhook-datree" ]
