apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: 'true'
    include.release.openshift.io/self-managed-high-availability: 'true'
    include.release.openshift.io/single-node-developer: 'true'
    network.operator.openshift.io/last-seen-state: '{"DaemonsetStates":[],"DeploymentStates":[],"StatefulsetStates":[]}'
    network.operator.openshift.io/relatedClusterObjects: ''
  creationTimestamp: '2023-05-26T09:47:26Z'
  generation: 1
  managedFields:
    - apiVersion: config.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:include.release.openshift.io/ibm-cloud-managed': {}
            'f:include.release.openshift.io/self-managed-high-availability': {}
            'f:include.release.openshift.io/single-node-developer': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"41fc205d-887a-4a62-bd45-17a9171b1d07"}': {}
        'f:spec': {}
      manager: cluster-version-operator
      operation: Update
      time: '2023-05-26T09:47:26Z'
    - apiVersion: config.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:extension': {}
      manager: cluster-version-operator
      operation: Update
      subresource: status
      time: '2023-05-26T09:47:27Z'
    - apiVersion: config.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:network.operator.openshift.io/last-seen-state': {}
            'f:network.operator.openshift.io/relatedClusterObjects': {}
      manager: cluster-network-operator
      operation: Update
      time: '2023-06-13T12:22:11Z'
    - apiVersion: config.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions': {}
          'f:relatedObjects': {}
          'f:versions': {}
      manager: cluster-network-operator
      operation: Update
      subresource: status
      time: '2023-06-14T09:11:00Z'
  name: network
  ownerReferences:
    - apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      name: version
      uid: 41fc205d-887a-4a62-bd45-17a9171b1d07
  resourceVersion: '17430080'
  uid: 85fbff6c-7122-4186-a015-8180c14ee471
