apiVersion: v1
kind: ServiceAccount
metadata:
  name: webhook-server-datree
  namespace: datree
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rolebinding:webhook-server-datree
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webhook-server-datree
subjects:
  - kind: ServiceAccount
    name: webhook-server-datree
    namespace: datree
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook-server-datree
rules:
  - apiGroups:
      - ""
    resources:
      - "nodes"
      - "namespaces"
    verbs:
      - "get"
      - "list"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server
  namespace: datree
  labels:
    env: testing
    app: webhook-server
    owner: datree
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webhook-server
  template:
    metadata:
      labels:
        app: webhook-server
    spec:
      serviceAccountName: webhook-server-datree
      containers:
        - name: server
          # caution: don't change the order of the environment variables
          # changing the order will harm resource patching
          env:
            - name: DATREE_TOKEN
              value: ${DATREE_TOKEN}
            - name: DATREE_POLICY
              value: ""
            - name: DATREE_VERBOSE
              value: ""
            - name: DATREE_OUTPUT
              value: ""
            - name: DATREE_NO_RECORD
              value: ""
            - name: DATREE_ENFORCE
              value: ""
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 25000
          livenessProbe:
            httpGet:
              path: /health
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          image: datree/admission-webhook:0.1.34
          imagePullPolicy: Always
          ports:
            - containerPort: 8443
              name: webhook-api
          volumeMounts:
            - name: webhook-tls-certs
              mountPath: /run/secrets/tls
              readOnly: true
            - name: webhook-config
              mountPath: /config
              readOnly: true
      volumes:
        - name: webhook-tls-certs
          secret:
            secretName: webhook-server-tls
        - name: webhook-config
          configMap:
            name: webhook-scanning-filters
            optional: true
---
apiVersion: v1
kind: Service
metadata:
  name: webhook-server
  namespace: datree
spec:
  selector:
    app: webhook-server
  ports:
    - port: 443
      targetPort: webhook-api
