apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: webhook-datree
webhooks:
  - name: webhook-server.datree.svc
    sideEffects: None
    timeoutSeconds: 30
    admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: webhook-server
        namespace: datree
        path: "/validate"
      caBundle: ${CA_PEM_B64}
    namespaceSelector:
      matchExpressions:
        - key: admission.datree/validate
          operator: DoesNotExist
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*"]
