{{- if and (.Values.datree.multiplePolicies) (not .Values.datree.configFromHelm)}}
    {{- fail "To use multiplePolicies please change configFromHelm to true" }}
{{- end }}
{{- if and (.Values.datree.multiplePolicies) (.Values.datree.policy)}}
    {{- fail "You can't use both policy and multiplePolicies at the same time" }}
{{- end }}
  
{{/* don't allow the same policy to be used more than once */}}
{{- if .Values.datree.multiplePolicies}}
    {{- $policyCount := dict}}
    {{- range $index, $policy := .Values.datree.multiplePolicies}}
        {{- $policyName := $policy.policy}}
        {{- if get $policyCount $policyName}}
            {{- fail (printf "datree.multiplePolicies: Policy \"%s\" cannot be used more than once. Refer to docs for more info: https://hub.datree.io/configuration/behavior#multipe-policies" $policyName)}}
        {{- else}}
            {{- $_ := set $policyCount $policyName true}}
        {{- end}}
    {{- end}}
{{- end }}
