apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-scan-job.yaml
  namespace: datree
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rolebinding:cluster-scan-job.yaml
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-scan-job.yaml
subjects:
  - kind: ServiceAccount
    name: cluster-scan-job.yaml
    namespace: datree
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-scan-job.yaml
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "get"
      - "list"
      - "watch"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: scan-job
  namespace: datree
  annotations:
    "helm.sh/hook": post-install
spec:
  template:
    spec:
      serviceAccountName: cluster-scan-job.yaml
      automountServiceAccountToken: false
      restartPolicy: Never
      containers:
        - name: scan-job
          env:
            - name: DATREE_TOKEN
              value: ${DATREE_TOKEN}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 25000
          image: tzlilswimmerdatree\/scan-job-test:0.0.1
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
  backoffLimit: 4
