apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-scan-job-service-account
  namespace: datree
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-scan-job-role
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "get"
      - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-scan-job-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-scan-job-role
subjects:
  - kind: ServiceAccount
    name: cluster-scan-job-service-account
    namespace: datree
---
apiVersion: batch/v1
kind: Job
metadata:
  name: scan-job
  namespace: datree
  annotations:
    "helm.sh/hook": post-install
spec:
  template:
    spec:
      serviceAccountName: cluster-scan-job-service-account
      restartPolicy: Never
      containers:
        - name: scan-job
          env:
            - name: DATREE_TOKEN
              value: {{.Values.datree.token}}
            - name: DATREE_POLICY
              value: {{.Values.datree.policy | default "Starter"}}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 25000
            seccompProfile:
              type: RuntimeDefault
          image: "{{ .Values.scan_job.image.repository }}:{{ .Values.scan_job.image.tag }}"
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 1000m
              memory: 256Mi
  backoffLimit: 4
