apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-scanning-filters
  namespace: {{ template "datree.namespace" . }}
data:
  datreeSkipList: |- 
    - (^kube-public$);(.*);(.*)
    - (^kube-node-lease$);(.*);(.*)
{{- range  .Values.datree.customSkipList }} 
    - {{ . }}
{{- end }}
