# used by the webhook server for leader election between multiple replicas	
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: datree-webhook-server-lease
  namespace: {{ template "datree.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
  {{- with .Values.customAnnotations }}
  {{ toYaml . | nindent 4 }}
  {{- end }}
  labels: {{ include "datree.labels" . | nindent 4 }}
spec:
  leaseDurationSeconds: 12	
