# used by the webhook server for leader election between multiple replicas	
apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  name: datree-webhook-server-lease
  namespace: {{ template "datree.namespace" . }}
  {{- with .Values.customAnnotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  labels: {{ include "datree.labels" . | nindent 4 }}
spec:
  leaseDurationSeconds: 12	
