apiVersion: batch/v1
kind: Job
metadata:
  name: datree-cleanup-namespaces-hook-post-uninstall
  namespace: {{template "datree.namespace" .}}
  labels: {{include "datree.labels" . | nindent 4}}
  annotations:
    "helm.sh/hook": post-uninstall
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels: {{include "datree.labels" . | nindent 8}}
    spec:
      restartPolicy: OnFailure
      serviceAccount: datree-cleanup-namespaces-hook-post-uninstall
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: kubectl-label
          image: "{{ .Values.hooks.labelNamespace.image.repository }}@{{ .Values.hooks.labelNamespace.image.sha }}"
          imagePullPolicy: {{.Values.hooks.labelNamespace.image.pullPolicy}}
          command:
            - >-
              label ns kube-system {{template "datree.namespace" .}} -datree.io/skip
              delete ns {{template "datree.namespace" .}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: datree-cleanup-namespaces-hook-post-uninstall
  namespace: {{template "datree.namespace" .}}
  labels: {{include "datree.labels" . | nindent 4}}
  annotations:
    "helm.sh/hook": post-uninstall
    "helm.sh/hook-delete-policy": hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datree-namespaces-update
  namespace: {{template "datree.namespace" .}}
  labels: {{include "datree.labels" . | nindent 4}}
  annotations:
    "helm.sh/hook": post-uninstall
    "helm.sh/hook-delete-policy": hook-succeeded
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - update
      - patch
    resourceNames:
      - kube-system
      - {{template "datree.namespace" .}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datree-namespaces-update
  namespace: {{template "datree.namespace" .}}
  labels: {{include "datree.labels" . | nindent 4}}
  annotations:
    "helm.sh/hook": post-uninstall
    "helm.sh/hook-delete-policy": hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datree-namespaces-update
subjects:
  - kind: ServiceAccount
    name: "datree-cleanup-namespaces-hook-post-uninstall"
    namespace: {{template "datree.namespace" . | quote}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datree-release-namespace-delete
  namespace: {{template "datree.namespace" .}}
  labels: {{include "datree.labels" . | nindent 4}}
  annotations:
    "helm.sh/hook": post-uninstall
    "helm.sh/hook-delete-policy": hook-succeeded
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - delete
    resourceNames:
      - {{template "datree.namespace" .}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datree-release-namespace-delete
  namespace: {{template "datree.namespace" .}}
  labels: {{include "datree.labels" . | nindent 4}}
  annotations:
    "helm.sh/hook": post-uninstall
    "helm.sh/hook-delete-policy": hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datree-release-namespace-delete
subjects:
  - kind: ServiceAccount
    name: "datree-cleanup-namespaces-hook-post-uninstall"
    namespace: {{template "datree.namespace" . | quote}}
