apiVersion: batch/v1
kind: Job
metadata:
  name: datree-label-namespaces-hook-post-install
  namespace: {{template "datree.namespace" .}}
  labels: {{include "datree.labels" . | nindent 4}}
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
    {{- with .Values.customAnnotations }}
    {{ toYaml . }}
    {{- end }}
spec:
  template:
    metadata:
      labels: {{include "datree.labels" . | nindent 8}}
      {{- with .Values.customAnnotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccount: datree-label-namespaces-hook-post-install
      restartPolicy: OnFailure
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: kubectl-label
          image: "{{ .Values.hooks.image.repository }}:{{ .Values.hooks.image.tag }}"
          imagePullPolicy: {{.Values.hooks.image.pullPolicy}}
          args:
            - label
            - ns
            - kube-system
            - {{template "datree.namespace" .}}
            - admission.datree/validate=skip
            - --overwrite
