apiVersion: batch/v1
kind: Job
metadata:
  name: datree-label-namespace
  namespace: {{template "datree.namespace" .}}
  labels: {{include "datree.labels" . | nindent 4}}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels: {{include "datree.labels" . | nindent 8}}
    spec:
      restartPolicy: OnFailure
      serviceAccount: datree-label-namespace
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: kubectl-datree-skip-label
          image: bitnami/kubectl:latest
          imagePullPolicy: Always
          args:
            - label
            - ns
            - kube-system
            - {{template "datree.namespace" .}}
            - datree.io/skip=true
            - --overwrite
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: datree-label-namespace
  namespace: {{template "datree.namespace" .}}
  labels: {{include "datree.labels" . | nindent 4}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datree-label-namespace-update
  namespace: {{template "datree.namespace" .}}
  labels: {{include "datree.labels" . | nindent 4}}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - update
      - patch
    resourceNames:
      - kube-system
      - {{template "datree.namespace" .}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datree-label-namespace-update
  namespace: {{template "datree.namespace" .}}
  labels: {{include "datree.labels" . | nindent 4}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datree-label-namespace-update
subjects:
  - kind: ServiceAccount
    name: datree-label-namespace
    namespace: {{template "datree.namespace" .}}
