apiVersion: batch/v1
kind: Job
metadata:
  name: datree-cleanup-namespaces-hook-pre-delete
  labels: {{include "datree.labels" . | nindent 4}}
  namespace: {{template "datree.namespace" .}}
  annotations: 
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
  {{- if .Values.customAnnotations }}
    {{- toYaml .Values.customAnnotations }}
  {{- end }}
spec:
  template:
    metadata:
      labels: {{include "datree.labels" . | nindent 8}}
      {{- if .Values.customAnnotations }}
      annotations: {{- toYaml .Values.customAnnotations | nindent 4 }}
      {{- end }}
    spec:
      restartPolicy: OnFailure
      serviceAccount: datree-cleanup-namespaces-hook-pre-delete
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: kubectl-label
          image: "{{ .Values.hooks.image.repository }}@{{ .Values.hooks.image.sha }}"
          imagePullPolicy: {{.Values.hooks.image.pullPolicy}}
          command:
            - sh
            - "-c"
            - >-
              kubectl delete validatingwebhookconfigurations.admissionregistration.k8s.io datree-webhook -n {{template "datree.namespace" .}};
              kubectl label ns kube-system {{template "datree.namespace" .}} datree.io/skip-;
