apiVersion: batch/v1
kind: Job
metadata:
  name: datree-label-namespaces-hook-post-install
  namespace: {{template "datree.namespace" .}}
  labels: {{include "datree.labels" . | nindent 4}}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
    {{- if .Values.customAnnotations }}
      {{- toYaml .Values.customAnnotations }}
    {{- end }}
spec:
  template:
    metadata:
      labels: {{include "datree.labels" . | nindent 8}}
      {{- if .Values.customAnnotations }}
      annotations: {{- toYaml .Values.customAnnotations | nindent 4 }}
      {{- end }}
    spec:
      serviceAccount: datree-label-namespaces-hook-post-install
      restartPolicy: OnFailure
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: kubectl-label
          image: "{{ .Values.hooks.labelNamespace.image.repository }}@{{ .Values.hooks.labelNamespace.image.sha }}"
          imagePullPolicy: {{.Values.hooks.labelNamespace.image.pullPolicy}}
          args:
            - label
            - ns
            - kube-system
            - {{template "datree.namespace" .}}
            - datree.io/skip=true
            - --overwrite
