apiVersion: batch/v1
kind: Job
metadata:
  name: datree-cleanup-namespaces-hook-pre-delete
  labels: {{include "datree.labels" . | nindent 4}}
  namespace: {{template "datree.namespace" .}}
  annotations: 
    "helm.sh/hook": pre-delete, pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
    {{- with .Values.customAnnotations }}
    {{ toYaml . }}
    {{- end}}
spec:
  ttlSecondsAfterFinished: {{.Values.hooks.ttlSecondsAfterFinished | default "1" }}
  template:
    metadata:
      labels: {{include "datree.labels" . | nindent 8}}
      {{- with .Values.customAnnotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: OnFailure
      serviceAccount: datree-cleanup-namespaces-hook-pre-delete
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: kubectl-label
          image: "{{ .Values.hooks.image.repository }}:{{ .Values.hooks.image.tag }}"
          imagePullPolicy: {{.Values.hooks.image.pullPolicy}}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}          
          command:
            - sh
            - "-c"
            - >-
              kubectl delete validatingwebhookconfigurations.admissionregistration.k8s.io datree-webhook -n {{template "datree.namespace" .}};
              kubectl label ns kube-system kube-public kube-node-lease {{template "datree.namespace" .}} admission.datree/validate-;
---
apiVersion: batch/v1
kind: Job
metadata:
  name: datree-uninstall-ping
  labels: {{include "datree.labels" . | nindent 4}}
  namespace: {{template "datree.namespace" .}}
  annotations: 
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
    {{- with .Values.customAnnotations }}
    {{ toYaml . }}
    {{- end}}
spec:
  ttlSecondsAfterFinished: {{.Values.hooks.ttlSecondsAfterFinished | default "1" }}
  template:
    metadata:
      labels: {{include "datree.labels" . | nindent 8}}
      {{- with .Values.customAnnotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      restartPolicy: OnFailure
      serviceAccount: datree-cleanup-ping-hook-pre-delete
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: datree-ping
          image: "kumahq/kubectl:v1.20.15"
          imagePullPolicy: {{.Values.hooks.image.pullPolicy}}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          command:
            - "/bin/sh"
            - "-c"
            - |
              if wget --quiet -qO- --header="Content-Type: application/json" \
                --post-data '{"clusterUuid":"'$(kubectl get ns kube-system -o jsonpath='{.metadata.uid}')'"}' \
                https://gateway.datree.io/cli/cluster/uninstall ; then 
                echo "Cluster uninstallation request sent successfully"; \
              else 
                echo "Error: Failed to send cluster uninstallation request"; \
              fi
