apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: datree-lease-reader
  labels: {{ include "datree.labels" . | nindent 4 }}
  {{- with .Values.customAnnotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - "leases"
    verbs:
      - "get"
      - "list"
