apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: datree-lease-reader
  labels: {{include "datree.labels" . | nindent 4}}
  {{- with .Values.customAnnotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: datree-lease-reader
subjects:
  - kind: ServiceAccount
    name: datree-wait-server-ready-hook-post-install
    namespace: "{{template "datree.namespace" .}}"
