apiVersion: v1
kind: Service
metadata:
  name: datree-webhook-server
  namespace: {{template "datree.namespace" .}}
  labels: {{include "datree.labels" . | nindent 4}}
  {{- if .Values.customAnnotations }}
  annotations: {{- toYaml .Values.customAnnotations | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: "datree-webhook-server"
  ports:
    - port: 443
      targetPort: webhook-api
