apiVersion: v1
kind: Service
metadata:
  name: datree-webhook-server
  namespace: {{template "datree.namespace" .}}
  labels: {{include "datree.labels" . | nindent 4}}
spec:
  selector:
    app: "datree-webhook-server"
  ports:
    - port: 443
      targetPort: webhook-api
