{{- if .Values.createSelfSignedCert }}
{{- $ca := genCA "/CN=Admission Controller Webhook Demo CA" 1827 -}}
{{- $altNames := list ( "webhook-server.datree.svc" ) -}}
{{- $cert := genSignedCert "/CN=webhook-server.datree.svc" nil $altNames 1827 $ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: datree-tls-ca 
  labels: {{ include "datree.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
data:
  tls.key: {{ $ca.Key | b64enc }}
  tls.crt: {{ $ca.Cert | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-tls
  labels: {{ include "datree.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace }}
  annotations:
    self-signed-cert: "true"
type: kubernetes.io/tls
data:
  tls.key: {{ $cert.Key | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: webhook-datree
webhooks:
  - name: webhook-server.datree.svc
    sideEffects: None
    timeoutSeconds: 30
    admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: webhook-server
        namespace: datree
        path: "/validate"
      caBundle: {{ $ca.Cert | b64enc }}
    namespaceSelector:
      matchExpressions:
        - key: admission.datree/validate
          operator: DoesNotExist
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*"]
{{- end -}}
