{{- if .Values.rbac.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{.Values.rbac.serviceAccount.name}}
  namespace: {{.Values.namespace}}
  labels: {{ include "datree.labels" . | nindent 4 }}
{{- end}}
