{{- if .Values.rbac.clusterRole.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{.Values.rbac.clusterRole.name}}
  labels: {{ include "datree.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - "nodes"
      - "namespaces"
    verbs:
      - "get"
      - "list"
{{- end}}