apiVersion: batch/v1
kind: Job
metadata:
  name: datree-wait-server-ready-hook-post-install
  namespace: {{template "datree.namespace" .}}
  labels: {{ include "datree.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
    {{- if .Values.customAnnotations }}
      {{- toYaml .Values.customAnnotations }}
    {{- end }}
spec:
  template:
    metadata:
      name: datree-wait-server-ready-hook-post-install
      labels: {{ include "datree.labels" . | nindent 8 }}
    spec:
      serviceAccountName: datree-wait-server-ready-hook-post-install
      restartPolicy: Never
      containers:
      - name: kubectl-client
        image: "{{ .Values.hooks.image.repository }}@{{ .Values.hooks.image.sha }}"
        imagePullPolicy: {{.Values.hooks.image.pullPolicy}}
        command:
          - sh
          - "-c"
          - >-
            kubectl wait --for=condition=ready pod -l app=datree-webhook-server --timeout="{{ default "180s" .Values.hooks.timeoutTime }}"