{{- $ca := genCA "/CN=Admission Controller Webhook Demo CA" 1827 -}}
{{- $altNames := list ( "datree-webhook-server.datree.svc" ) -}}
{{- $cert := genSignedCert "/CN=datree-webhook-server.datree.svc" nil $altNames 1827 $ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: datree-ca-tls
  labels: {{ include "datree.labels" . | nindent 4 }}
  namespace: {{ template "datree.namespace" . }}
  {{- if .Values.customAnnotations }}
  annotations: {{- toYaml .Values.customAnnotations | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.key: {{ $ca.Key | b64enc }}
  tls.crt: {{ $ca.Cert | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-tls
  labels: {{ include "datree.labels" . | nindent 4 }}
  namespace: {{ template "datree.namespace" . }}
  annotations:
    self-signed-cert: "true"
    {{- if .Values.customAnnotations }}
      {{- toYaml .Values.customAnnotations}}
    {{- end }}
type: kubernetes.io/tls
data:
  tls.key: {{ $cert.Key | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: datree-webhook
  annotations:
    "helm.sh/hook": post-install, post-upgrade
    "helm.sh/hook-weight": "-5"
    {{- if .Values.customAnnotations }}
      {{- toYaml .Values.customAnnotations}}
    {{- end }}
webhooks:
  - name: webhook-server.datree.svc
    sideEffects: None
    timeoutSeconds: 30
    admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      service:
        name: datree-webhook-server
        namespace: {{ template "datree.namespace" . }}
        path: "/validate"
      caBundle: {{ $ca.Cert | b64enc }}
    namespaceSelector:
      matchExpressions:
        - key: admission.datree/validate
          operator: DoesNotExist
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*"]
