name: go mod tidy validation
on:
  pull_request:
    branches:
      - main
jobs:
  go_mod_tidy_validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: run go mod tidy
        run: go mod tidy
      - name: Check for file changes
        shell: bash
        run: |
          if [ -n "$(git diff)" ]; then
            echo "::error::go-mod-tidy-validation failed, did you forget to run \"go mod tidy\"?"
            exit 1
          fi
