name: Release Charts

on:
  workflow_run:
    workflows: ["Release to Prod"]
    types:
      - completed

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{secrets.DATREE_CI_GH_TOKEN}}
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "datree-ci"
          git config user.email "ci@datree.io"
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0
      - name: Set Chart Version env
        run: |
          NEW_CHART_VERSION=$(yq e '.version' ./charts/datree-admission-webhook/Chart.yaml | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo "NEW_CHART_VERSION=$NEW_CHART_VERSION" >> $GITHUB_ENV
      - name: Custom bump versions
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq e -i '.version= "${{ env.NEW_CHART_VERSION }}"' ./charts/datree-admission-webhook/Chart.yaml
      - name: Auto commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'build: Automated Change - Bump helm chart version to "${{ env.NEW_CHART_VERSION }}"'
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        env:
          CR_TOKEN: "${{ secrets.DATREE_CI_GH_TOKEN }}"
