name: Niv test
on:
  push:
    branches: 
      - DAT-4673**
jobs:
  armv7_job:
    # The host should always be Linux
    runs-on: ubuntu-20.04
    env:
      DOCKERHUB_ORGANIZATION: datree
      DOCKERHUB_REPO: webhook-staging
    name: Build on ubuntu-latest aarch64
    steps:
      - uses: actions/checkout@v3
      - name: Define release version
        id: define_version
        run: |-
          OUTPUT_VERSION=$(bash scripts/get_last_short_commit_hash.sh)
          echo "detected version = $OUTPUT_VERSION"
          echo "version=$OUTPUT_VERSION" >> $GITHUB_OUTPUT
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: none
          distro: none
          base_image: docker:cli
          shell: /bin/sh
          install: apk update && apk add git
          run: |
            git --version
            echo -e "steps.define_version.outputs.version: ${{ steps.define_version.outputs.version }}"
            echo -e "env.DOCKERHUB_ORGANIZATION: ${{ env.DOCKERHUB_ORGANIZATION }}"
            echo -e "env.DOCKERHUB_REPO: ${{ env.DOCKERHUB_REPO }}"
            docker build --quiet --build-arg "BUILD_ENVIRONMENT=staging" --build-arg "WEBHOOK_VERSION=${{ steps.define_version.outputs.version }}" -t ${{ env.DOCKERHUB_ORGANIZATION }}/${{ env.DOCKERHUB_REPO }}:${{ steps.define_version.outputs.version }} -t ${{ env.DOCKERHUB_ORGANIZATION }}/${{ env.DOCKERHUB_REPO }}:latest .
            docker images -a
            docker image inspect --format "{{.ID}} {{.RepoTags}} {{.Architecture}}" $(docker image ls -q)

      # - name: Get the output
      #   # Echo the `uname` output parameter from the `runcmd` step
      #   run: |
      #     echo "The uname output was ${{ steps.runcmd.outputs.uname }}"            
            
      # - name: Define release version
      #   id: define_version
      #   run: |-
      #     OUTPUT_VERSION=$(bash scripts/get_last_short_commit_hash.sh)
      #     echo "detected version = $OUTPUT_VERSION"
      #     echo "version=$OUTPUT_VERSION" >> $GITHUB_OUTPUT
      
      # - uses: docker/setup-buildx-action@v2
      # - name: Log in to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      # - name: Build and push datree image to registries
      #   uses: docker/build-push-action@v3
      #   with:
      #     build-args: |-
      #       "BUILD_ENVIRONMENT=staging"
      #       "WEBHOOK_VERSION=${{ steps.define_version.outputs.version }}"
      #     context: .
      #     file: ./Dockerfile
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: |
      #       ${{ env.DOCKERHUB_ORGANIZATION }}/${{ env.DOCKERHUB_REPO }}:${{ steps.define_version.outputs.version }}
      #       ${{ env.DOCKERHUB_ORGANIZATION }}/${{ env.DOCKERHUB_REPO }}:latest
