name: Release Helm Chart Steps

on:
  workflow_call:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      chart_version: ${{ steps.set_chart_version.outputs.chart_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{secrets.DATREE_CI_GH_TOKEN}}
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "datree-ci"
          git config user.email "ci@datree.io"
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0
      - name: Set Chart Version env
        id: set_chart_version
        run: |
          NEW_CHART_VERSION=$(yq e '.version' ./charts/datree-admission-webhook/Chart.yaml | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo "NEW_CHART_VERSION=$NEW_CHART_VERSION" >> $GITHUB_ENV
          echo "chart_version=$NEW_CHART_VERSION" >> $GITHUB_OUTPUT
      - name: Custom bump versions
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq e -i '.version= "${{ env.NEW_CHART_VERSION }}"' ./charts/datree-admission-webhook/Chart.yaml
      - name: Auto commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'build: Automated Change - Bump helm chart version to "${{ env.NEW_CHART_VERSION }}"'
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        env:
          CR_TOKEN: "${{ secrets.DATREE_CI_GH_TOKEN }}"
  update-docs:
    runs-on: ubuntu-latest
    name: update docs after the release
    needs: release
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.DATREE_CI_GH_TOKEN}}
          repository: datreeio/docs
      - name: Replace version in docs
        run: |
          sed -E 's/datree-admission-webhook --revision [0-9.]+/datree-admission-webhook --revision ${{ needs.release.outputs.chart_version }}/' ./docs/welcome/getting-started/index.mdx > ~/getting_started_index_temp.mdx && mv ~/getting_started_index_temp.mdx ./docs/welcome/getting-started/index.mdx
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{secrets.DATREE_CI_GH_TOKEN}}
          commit-message: "docs: update webhook version to ${{ needs.release.outputs.chart_version }}"
          title: "docs: update webhook version to ${{ needs.release.outputs.chart_version }}"
          body: "docs: update webhook version to ${{ needs.release.outputs.chart_version }}"
          branch: "docs/update-webhook-version-${{ needs.release.outputs.chart_version }}"
          branch-suffix: "timestamp"
          delete-branch: true
          labels: "docs"
          reviewers: "datreeio/product"
