name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
      - name: Build
        run: go build -v ./...
      - name: Test
        run: DATREE_ENFORCE="true" go test -v ./...
